language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
  - "8"
branches:
  only:
    - master
    - v1.0.0
before_install:
  - git submodule update --init --recursive
script:
  - "npm run cover"
  - "npm run lint"
